In [5]:
import numpy as np
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/gulsh/anaconda3/Library/include
    lib directory: C:/Users/gulsh/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

In [7]:
null_vector =np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
vector = np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
vector = np.arange(10)
reversed_vector = vector[::-1]
print(reversed_vector)

[9 8 7 6 5 4 3 2 1 0]


In [17]:
n=8
checkerboard= np.zeros((n,n), dtype=int)
checkerboard[1::2, ::2]=1
checkerboard[::2,1::2]=1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
n=4
m=2
array= np.random.randint(0,10,(n,n))
sorted_array = array[array[:,m].argsort()]
print(array)
print(sorted_array)

[[3 7 0 4]
 [3 3 7 4]
 [3 2 6 2]
 [2 5 0 9]]
[[3 7 0 4]
 [2 5 0 9]
 [3 2 6 2]
 [3 3 7 4]]


In [23]:
n=4
array= np.fromfunction(lambda i, j: i+j, (n,n), dtype=int)
print(array)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [25]:
index= np.unravel_index(99,(6,7,8))
print(index)

(1, 5, 3)


In [27]:
A = np.random.random((5,3))
B= np.random.random((3,2))
product=np.dot(A,B)
print(product)

[[0.29732903 0.20124909]
 [0.66290783 0.33738206]
 [0.40270461 0.62875394]
 [0.5776548  0.33173662]
 [0.88101148 0.86943253]]


In [29]:
vector= np.random.random(10)
vector[vector.argmax()]=0
print(vector)

[0.73716588 0.78301361 0.62710078 0.22805208 0.         0.52045602
 0.01869531 0.43201831 0.27393858 0.05506003]


In [32]:
array=np.random.random(10)
scalar=0.5
closest_value = array[np.abs(array - scalar).argmin()]
print(array)
print(f"Closest value to {scalar}: {closest_value}")

[0.00366709 0.09439264 0.7890355  0.30955135 0.37023743 0.97324022
 0.27898964 0.22368742 0.48371989 0.60827755]
Closest value to 0.5: 0.4837198877210538


In [38]:
matrix= np.random.random((4,4))
row_mean = matrix.mean(axis=1, keepdims=True)
result = matrix - row_mean
print(matrix)
print(result)

[[0.50238172 0.47733853 0.17166114 0.37395071]
 [0.14013824 0.96897677 0.21519837 0.77537161]
 [0.27293713 0.03388306 0.29950815 0.13423603]
 [0.43275323 0.15888829 0.77766313 0.22720553]]
[[ 0.1210487   0.09600551 -0.20967189 -0.00738232]
 [-0.38478301  0.44405552 -0.30972288  0.25045037]
 [ 0.08779604 -0.15125803  0.11436706 -0.05090506]
 [ 0.03362569 -0.24023925  0.37853558 -0.17192202]]


In [42]:
vector= np.zeros(10)
indices = np.array([0,1,2,2,3,4,4])
vector[np.unique(indices)] +=1
print(vector)

[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [48]:
array = np.random.randint(0,10,20)
most_frequent = np.bincount(array).argmax()
print(array)
print(most_frequent)

[8 2 9 2 7 2 2 7 8 1 4 7 4 9 6 1 5 6 5 1]
2


In [56]:
matrix= np.random.random((10,10))
i = np.arange(8)[:, None] + np.arange(3)
j = np.arange(8)[:, None] + np.arange(3)
blocks = matrix[i[:, :, None], j[:, None, :]]
print(matrix)
print(blocks)

[[0.33495622 0.30649689 0.48598878 0.9522692  0.50997237 0.96415632
  0.8564408  0.29504243 0.47745007 0.89642635]
 [0.84953254 0.99343156 0.63129135 0.84360009 0.80095385 0.43014378
  0.02871189 0.73980196 0.10010722 0.91504808]
 [0.17282638 0.35785612 0.42507669 0.23401853 0.40190336 0.93929109
  0.69299988 0.04052345 0.60429508 0.0085553 ]
 [0.67062685 0.65472536 0.93140997 0.13862484 0.11912925 0.09552874
  0.52630227 0.9281824  0.4697357  0.11785227]
 [0.89908181 0.66426383 0.72739614 0.67813792 0.09553212 0.12719458
  0.39219249 0.5330329  0.81301779 0.39301056]
 [0.88454682 0.19972971 0.50172089 0.42958795 0.75647261 0.92616947
  0.31525746 0.95024926 0.90726825 0.5477193 ]
 [0.94598113 0.74629782 0.45624252 0.20824286 0.56570009 0.62794204
  0.95721451 0.31912848 0.9296476  0.91459933]
 [0.14363386 0.34873731 0.61071699 0.7983465  0.82844721 0.27391037
  0.05856906 0.53266619 0.94974531 0.69479836]
 [0.11390258 0.44552623 0.65918673 0.39368753 0.38815791 0.89777831
  0.28462727

In [60]:
matrix = np.random.random((4,4))
rank = np.linalg.matrix_rank(matrix)
trace = np.trace(matrix)
determinant = np.linalg.det(matrix)
print(f"Rank is {rank}, Trace is {trace}, Determinant is {determinant}")

Rank is 4, Trace is 2.077344216036452, Determinant is -0.011919355519899186
